import java.util.ArrayList;
import java.util.List;

import org.assertj.core.api.SoftAssertions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class HiRCAChinese23 {

	public List<String> chineseHTMLReport1stPath_hc23 (WebDriver driver, SoftAssertions softly) throws Exception {

		WebDriverWait wait = new WebDriverWait(driver,30);
		List <String> verifyChinese = new ArrayList<String>();
		//3.2 table rows
		String r315 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r315).as("test data").contains("3.2.1 组长强化标准方面的管理能力不足");
		String r316 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r316).as("test data").contains("不适用");
		String r317 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li"))).getText();
		softly.assertThat(r317).as("test data").contains("访谈同事？");
		String r318 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r318).as("test data").contains("监督管理方面的培训");
		String r319 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r319).as("test data").contains("监督行为规范的管理");
		String r320 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r320).as("test data").contains("3.2.2 组长绩效反馈方面的管理能力不足");
		String r321 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r321).as("test data").contains("不适用");
		String r322 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r322).as("test data").contains("访谈同事？");
		String r323 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r323).as("test data").contains("监督管理方面的培训");
		String r324 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r324).as("test data").contains("监督行为规范的管理");
		String r325 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r325).as("test data").contains("3.2.3 组长召开经验反馈的管理技能不足");
		String r326 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r326).as("test data").contains("不适用");
		String r327 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li"))).getText();
		softly.assertThat(r327).as("test data").contains("访谈同事？");
		String r328 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r328).as("test data").contains("监督管理方面的培训");
		String r329 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r329).as("test data").contains("监督行为规范的管理");
		String r330 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r330).as("test data").contains("3.2.4 组长在岗培训方面管理能力不足");
		String r331 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r331).as("test data").contains("不适用");
		String r332 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r332).as("test data").contains("访谈同事？");
		String r333 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r333).as("test data").contains("监督管理方面的培训");
		String r334 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r334).as("test data").contains("监督行为规范的管理");
		String r335 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r335).as("test data").contains("3.2.5 组长对团队缺点认识不足，缺乏相应弥补措施");
		String r336 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r336).as("test data").contains("不适用");
		String r337 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r337).as("test data").contains("访谈同事？");
		String r338 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r338).as("test data").contains("监督管理方面的培训");
		String r339 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r339).as("test data").contains("监督行为规范的管理");
		String r340 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r340).as("test data").contains("3.2.6 组长发出指令和后续贯彻的沟通及协调能力不足");
		String r341 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r341).as("test data").contains("不适用");
		String r342 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li"))).getText();
		softly.assertThat(r342).as("test data").contains("访谈下属？");
		String r343 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r343).as("test data").contains("监督管理方面的培训");
		String r344 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r344).as("test data").contains("监督行为规范的管理");
		//3.11
		String r345 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r345).as("test data").contains("3.11.1 绩效跟踪与趋势分析(PM&T)以及给员工的反馈不到位");
		String r346 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r346).as("test data").contains("不适用");
		String r347 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li"))).getText();
		softly.assertThat(r347).as("test data").contains("向员工反馈绩效趋势结果？");
		String r348 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r348).as("test data").contains("完善趋势分析体系");
		String r349 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r349).as("test data").contains("完善趋势反馈");
		String r350 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[1]"))).getText();
		softly.assertThat(r350).as("test data").contains("3.11.2 即时反馈和持续强化(IF&CR)的管理技能不到位");
		String r351 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[2]"))).getText();
		softly.assertThat(r351).as("test data").contains("不适用");
		String r352 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r352).as("test data").contains("花在现场观察和监督工作的时间是否足够？");
		String r353 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r353).as("test data").contains("标准的持续强化？");
		String r354 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r354).as("test data").contains("观察到偏差时，是否及时反馈？");
		String r355 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[4]"))).getText();
		softly.assertThat(r355).as("test data").contains("正面反馈多余负面反馈？");
		String r356 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r356).as("test data").contains("提高主管人员的问责意识");
		String r357 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r357).as("test data").contains("改善关于管理技能的培训");
		String r358 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r358).as("test data").contains("3.11.3 用于绩效控制的奖惩制度不到位");
		String r359 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r359).as("test data").contains("不适用");
		String r360 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r360).as("test data").contains("奖惩制度是否及时？");
		String r361 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r361).as("test data").contains("奖惩制度是否公平？");
		String r362 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r362).as("test data").contains("奖惩制度是否坚定？");
		String r363 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[4]/ul/li"))).getText();
		softly.assertThat(r363).as("test data").contains("完善奖惩制度");
		String r364 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[1]"))).getText();
		softly.assertThat(r364).as("test data").contains("3.11.4 问题报告、RCA和纠正行动不到位，给员工的反馈不到位");
		String r365 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[2]"))).getText();
		softly.assertThat(r365).as("test data").contains("不适用");
		String r366 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[3]/ul/li"))).getText();
		softly.assertThat(r366).as("test data").contains("核实汇报分析的小事件数量比例以及受伤数量");
		String r367 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r367).as("test data").contains("在问题报告政策中要求包含一切问题和及时性");
		String r368 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r368).as("test data").contains("RCA培训和授权");
		String r369 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[3]"))).getText();
		softly.assertThat(r369).as("test data").contains("改善对RCA结果的反馈");
		String r370 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[1]"))).getText();
		softly.assertThat(r370).as("test data").contains("3.11.5 现场观察不充分，给员工的反馈不到位");
		String r371 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[2]"))).getText();
		softly.assertThat(r371).as("test data").contains("不适用");
		String r372 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r372).as("test data").contains("各部门均建立了现场观察指导制度？");
		String r373 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r373).as("test data").contains("对过去现场观察指导结果的有效性审查？");
		String r374 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r374).as("test data").contains("花在现场观察指导上的时间？");
		String r375 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r375).as("test data").contains("针对现场观察结果，改善给员工的反馈");
		String r376 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r376).as("test data").contains("改进现场观察员的制度和TQA");
		//1.10
		String r377 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[14]/td[1]"))).getText();
		softly.assertThat(r377).as("test data").contains("1.10 若有开班前会、工前会、交底会，为何犯错者未能意识到这个风险且缓解？");
		verifyChinese.add(r377);
		String r378 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[14]/td[2]"))).getText();
		softly.assertThat(r378).as("test data").contains("没有专心参与");
		verifyChinese.add(r378);
		String r379 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[14]/td[3]"))).getText();
		softly.assertThat(r379).as("test data").contains("不适用");
		//1.11
		String r380 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[15]/td[1]"))).getText();
		softly.assertThat(r380).as("test data").contains("1.11 这个错为何是现在发生而不是以前发生？");
		verifyChinese.add(r380);
		String r381 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[15]/td[2]"))).getText();
		softly.assertThat(r381).as("test data").contains("新程序的使用未有妥当培训");
		verifyChinese.add(r381);
		String r382 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[15]/td[3]"))).getText();
		softly.assertThat(r382).as("test data").contains("不适用");
		//3.9 table heading
		String heading19 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading19).as("test data").contains("可能促成因素");
		String heading20 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading20).as("test data").contains("支持证据");
		String heading21 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading21).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading22 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading22).as("test data").contains("可能的纠正行动");*/
		//3.9 table rows
		String r383 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r383).as("test data").contains("3.9.1 培训材料在适用性、及时性或实用性方面有所欠缺");
		String r2291 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r2291).as("test data").contains("不适用");
		String r2301 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2301).as("test data").contains("与类似组织对标？");
		String r2311 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2311).as("test data").contains("通过现场观察审查培训效果？");
		String r2321 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r2321).as("test data").contains("加强培训资源");
		String r2331 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r2331).as("test data").contains("开展作业任务分析，从而使培训材料、课程及时间与员工执行的任务相匹配");
		String r2341 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r2341).as("test data").contains("3.9.2 复训频率不高(>> 一年)");
		String r2351 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r2351).as("test data").contains("不适用");
		String r2361 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2361).as("test data").contains("复训频率是否是根据复杂程度和使用频率来确定的？");
		String r2371 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2371).as("test data").contains("复训的形式？");
		String r2381 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li"))).getText();
		softly.assertThat(r2381).as("test data").contains("增加复训频率，改善复训形式");
		String r2391 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r2391).as("test data").contains("3.9.3 部门管理层未充分参与培训材料的编写和培训的实施");
		String r2401 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r2401).as("test data").contains("不适用");
		String r2411 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2411).as("test data").contains("部门经理审查关于培训材料的意见？");
		String r2421 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2421).as("test data").contains("部门经理监督对上课情况？");
		String r2431 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li"))).getText();
		softly.assertThat(r2431).as("test data").contains("完善关于管理层参与培训材料编写或培训实施的相关要求");
		String r2441 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r2441).as("test data").contains("3.9.4 未将经验教训充分包含到培训中");
		String r2451 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r2451).as("test data").contains("不适用");
		String r2461 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r2461).as("test data").contains("审查对以往事件根本原因和共同原因的调查情况（从屏障、失误陷阱等角度）？");
		String r2471 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li"))).getText();
		softly.assertThat(r2471).as("test data").contains("提高对培训效果的审查");
		String r2481 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r2481).as("test data").contains("3.9.5 所需培训开展不充分（脱岗）");
		String r2491 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r2491).as("test data").contains("不适用");
		String r2501 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2501).as("test data").contains("培训签到表，%员工接受了培训？");
		String r2511 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2511).as("test data").contains("现场承包商没有经过培训？");
		String r2521 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r2521).as("test data").contains("完善承包商控制方针");
		String r2531 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r2531).as("test data").contains("完善培训资源");
		String r2541 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r2541).as("test data").contains("3.9.6 所需培训开展不充分（在岗）");
		String r2551 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r2551).as("test data").contains("不适用");
		String r2561 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2561).as("test data").contains("在岗培训方针？");
		String r2571 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2571).as("test data").contains("经验不足的员工没有经过培训？");
		String r2581 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r2581).as("test data").contains("完善在岗培训方针");
		String r2591 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r2591).as("test data").contains("完善培训资源");
		//1.12
		String r3801 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[17]/td[1]"))).getText();
		softly.assertThat(r3801).as("test data").contains("1.12 若班前会、工前会或交底会未执行，为什么？");
		verifyChinese.add(r3801);
		String r3811 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[17]/td[2]"))).getText();
		softly.assertThat(r3811).as("test data").contains("违反程序规定未执行");
		verifyChinese.add(r3811);
		String r3821 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[17]/td[3]"))).getText();
		softly.assertThat(r3821).as("test data").contains("不适用");
		//1.13
		String r38011 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[18]/td[1]"))).getText();
		softly.assertThat(r38011).as("test data").contains("1.13 错误的发生是否存在易出错精神状态或是高风险状态？");
		verifyChinese.add(r38011);
		String r38111 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[18]/td[2]"))).getText();
		softly.assertThat(r38111).as("test data").contains("没有，请重新思考您的答案");
		verifyChinese.add(r38111);
		String r384 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[18]/td[3]"))).getText();
		softly.assertThat(r384).as("test data").contains("不适用");
		//1.14
		String r385= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[19]/td[1]"))).getText();
		softly.assertThat(r385).as("test data").contains("1.14 组长是否固定开展经验反馈？");
		verifyChinese.add(r385);
		String r386 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[19]/td[2]"))).getText();
		softly.assertThat(r386).as("test data").contains("没有，但其他组长有");
		verifyChinese.add(r386);
		String r387 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[19]/td[3]"))).getText();
		softly.assertThat(r387).as("test data").contains("不适用");
		//3.2 table heading
		String heading221 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading221).as("test data").contains("可能促成因素");
		String heading23 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading23).as("test data").contains("支持证据");
		String heading24 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading24).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading25 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading25).as("test data").contains("可能的纠正行动");*/
		//3.2 table rows
		String r3151 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r3151).as("test data").contains("3.2.1 组长强化标准方面的管理能力不足");
		String r3161 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r3161).as("test data").contains("不适用");
		String r3171 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li"))).getText();
		softly.assertThat(r3171).as("test data").contains("访谈同事？");
		String r3181 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3181).as("test data").contains("监督管理方面的培训");
		String r3191 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3191).as("test data").contains("监督行为规范的管理");
		String r388 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r388).as("test data").contains("3.2.2 组长绩效反馈方面的管理能力不足");
		String r389 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r389).as("test data").contains("不适用");
		String r390 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r390).as("test data").contains("访谈同事？");
		String r391 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r391).as("test data").contains("监督管理方面的培训");
		String r392 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r392).as("test data").contains("监督行为规范的管理");
		String r393 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r393).as("test data").contains("3.2.3 组长召开经验反馈的管理技能不足");
		String r394 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r394).as("test data").contains("不适用");
		String r395 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li"))).getText();
		softly.assertThat(r395).as("test data").contains("访谈同事？");
		String r396 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r396).as("test data").contains("监督管理方面的培训");
		String r3291 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3291).as("test data").contains("监督行为规范的管理");
		String r3301 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r3301).as("test data").contains("3.2.4 组长在岗培训方面管理能力不足");
		String r3311 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r3311).as("test data").contains("不适用");
		String r3321 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r3321).as("test data").contains("访谈同事？");
		String r3331 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3331).as("test data").contains("监督管理方面的培训");
		String r3341 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3341).as("test data").contains("监督行为规范的管理");
		String r3351 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r3351).as("test data").contains("3.2.5 组长对团队缺点认识不足，缺乏相应弥补措施");
		String r3361 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r3361).as("test data").contains("不适用");
		String r3371 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r3371).as("test data").contains("访谈同事？");
		String r3381 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3381).as("test data").contains("监督管理方面的培训");
		String r3391 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3391).as("test data").contains("监督行为规范的管理");
		String r3401 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r3401).as("test data").contains("3.2.6 组长发出指令和后续贯彻的沟通及协调能力不足");
		String r3411 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r3411).as("test data").contains("不适用");
		String r3421 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li"))).getText();
		softly.assertThat(r3421).as("test data").contains("访谈下属？");
		String r3431 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3431).as("test data").contains("监督管理方面的培训");
		String r3441 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3441).as("test data").contains("监督行为规范的管理");
		//1.15
		String r397= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[21]/td[1]"))).getText();
		softly.assertThat(r397).as("test data").contains("1.15 始发事件是否有单项弱点？");
		verifyChinese.add(r397);
		String r398 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[21]/td[2]"))).getText();
		softly.assertThat(r398).as("test data").contains("有，但未提前识别");
		verifyChinese.add(r398);
		String r399 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[21]/td[3]"))).getText();
		softly.assertThat(r399).as("test data").contains("不适用");
		//3.6 table heading
		String heading27 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading27).as("test data").contains("可能促成因素");
		String heading28 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading28).as("test data").contains("支持证据");
		String heading29 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading29).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading30 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading30).as("test data").contains("可能的纠正行动");*/
		//3.6 table rows
		String r400 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r400).as("test data").contains("3.6.1 要求有遗漏");
		String r401 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r401).as("test data").contains("不适用");
		String r402 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r402).as("test data").contains("规范和标准？");
		String r403 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r403).as("test data").contains("规范和标准？");
		String r404 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r404).as("test data").contains("与其他项目之间的接口要求？");
		String r405 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r405).as("test data").contains("完善规则");
		String r406 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r406).as("test data").contains("开展程序设计方面的培训");
		String r407 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r407).as("test data").contains("3.6.2 运行条件有遗漏");
		String r408 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r408).as("test data").contains("不适用");
		String r409 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r409).as("test data").contains("规则适用的运行条件范围？");
		String r410 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r410).as("test data").contains("进入规则的前提条件？");
		String r411 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r411).as("test data").contains("退出规则的条件？");
		String r412 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r412).as("test data").contains("完善规则");
		String r413 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r413).as("test data").contains("开展程序设计方面的培训");
		String r414 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r414).as("test data").contains("3.6.3 假设有遗漏");
		String r415 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r415).as("test data").contains("不适用");
		String r416 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r416).as("test data").contains("假设未予以说明？");
		String r417 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r417).as("test data").contains("未要求在任务完成前对假设进行验证？");
		String r418 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r418).as("test data").contains("对未经验证的假设没有制定缓解措施？");
		String r419 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r419).as("test data").contains("完善规则");
		String r420 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r420).as("test data").contains("开展程序设计方面的培训");
		String r421 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r421).as("test data").contains("3.6.4 范围有遗漏");
		String r422 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r422).as("test data").contains("不适用");
		String r423 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r423).as("test data").contains("使用通用规则，缺少针对各种特殊情况的具体描述？");
		String r424 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r424).as("test data").contains("步骤遗漏？");
		String r425 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r425).as("test data").contains("遗漏了碰到异常情况时需采取的行动？");
		String r426 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r426).as("test data").contains("完善规则");
		String r427 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r427).as("test data").contains("开展程序设计方面的培训");
		String r428 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r428).as("test data").contains("3.6.5 试验或测量有遗漏");
		String r429 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r429).as("test data").contains("不适用");
		String r430 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r430).as("test data").contains("遗漏了用于验收是否正确执行的相关试验或测量？");
		String r431 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r431).as("test data").contains("完善规则");
		String r432 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r432).as("test data").contains("开展程序设计方面的培训");
		String r433 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r433).as("test data").contains("3.6.6 遗漏以下信息: (1) 目的; (2) 先决条件; (3) 定义; (4) 经验反馈用");
		softly.assertThat(r433).as("test data").contains("不准做清单");
		softly.assertThat(r433).as("test data").contains("体现; (5) 参考资料; (6) 要求使用者反馈");
		String r434 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r434).as("test data").contains("不适用");
		String r435 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r435).as("test data").contains("调查程序编写者");
		String r436 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r436).as("test data").contains("调查程序设计编写培训");
		String r437 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r437).as("test data").contains("开展程序设计编写培训");
		String r438 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r438).as("test data").contains("改善程序编写导则");
		String r439 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r439).as("test data").contains("3.6.7 审查不到位导致制度有遗漏项");
		String r440 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r440).as("test data").contains("不适用");
		String r441 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r441).as("test data").contains("调查程序审查者");
		String r442 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r442).as("test data").contains("调查程序审查培训");
		String r443 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li"))).getText();
		softly.assertThat(r443).as("test data").contains("开展程序审查培训");
		String r444 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[1]"))).getText();
		softly.assertThat(r444).as("test data").contains("3.6.8 根本原因分析不到位导致制度有遗漏项");
		String r445 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[2]"))).getText();
		softly.assertThat(r445).as("test data").contains("不适用");
		String r446 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r446).as("test data").contains("调查事件调查者");
		String r447 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r447).as("test data").contains("调查事件根本原因培训");
		String r448 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li"))).getText();
		softly.assertThat(r448).as("test data").contains("开展根本原因培训");
		String r449 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r449).as("test data").contains("3.6.9 纠正措施执行不到位导致制度有遗漏项");
		String r450 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r450).as("test data").contains("不适用");
		String r451 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r451).as("test data").contains("调查纠正措施主管");
		String r452 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r452).as("test data").contains("调查纠正措施制度缺陷");
		String r453 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[4]/ul/li"))).getText();
		softly.assertThat(r453).as("test data").contains("改善纠正措施制度的监督与执行");
		//1.16
		String r454= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[23]/td[1]"))).getText();
		softly.assertThat(r454).as("test data").contains("1.16 事件是与组长监督管理不当有关？");
		verifyChinese.add(r454);
		String r455 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[23]/td[2]"))).getText();
		softly.assertThat(r455).as("test data").contains("是，跟其他组长相比下有缺失");
		verifyChinese.add(r455);
		String r456 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[23]/td[3]"))).getText();
		softly.assertThat(r456).as("test data").contains("不适用");
		//3.2 table heading
		String heading31 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading31).as("test data").contains("可能促成因素");
		String heading32 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading32).as("test data").contains("支持证据");
		String heading33 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading33).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading34 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading34).as("test data").contains("可能的纠正行动");*/
		//3.2 table rows
		String r457 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r457).as("test data").contains("3.2.1 组长强化标准方面的管理能力不足");
		String r458 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r458).as("test data").contains("不适用");
		String r459 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li"))).getText();
		softly.assertThat(r459).as("test data").contains("访谈同事？");
		String r460 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r460).as("test data").contains("监督管理方面的培训");
		String r461 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r461).as("test data").contains("监督行为规范的管理");
		String r462 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r462).as("test data").contains("3.2.2 组长绩效反馈方面的管理能力不足");
		String r463 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r463).as("test data").contains("不适用");
		String r464 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r464).as("test data").contains("访谈同事？");
		String r465 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r465).as("test data").contains("监督管理方面的培训");
		String r466 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r466).as("test data").contains("监督行为规范的管理");
		String r467 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r467).as("test data").contains("3.2.3 组长召开经验反馈的管理技能不足");
		String r468 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r468).as("test data").contains("不适用");
		String r469 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li"))).getText();
		softly.assertThat(r469).as("test data").contains("访谈同事？");
		String r470 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r470).as("test data").contains("监督管理方面的培训");
		String r471 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r471).as("test data").contains("监督行为规范的管理");
		String r472 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r472).as("test data").contains("3.2.4 组长在岗培训方面管理能力不足");
		String r473 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r473).as("test data").contains("不适用");
		String r474 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r474).as("test data").contains("访谈同事？");
		String r475 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r475).as("test data").contains("监督管理方面的培训");
		String r476 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r476).as("test data").contains("监督行为规范的管理");
		String r477 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r477).as("test data").contains("3.2.5 组长对团队缺点认识不足，缺乏相应弥补措施");
		String r478 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r478).as("test data").contains("不适用");
		String r479 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r479).as("test data").contains("访谈同事？");
		String r480 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r480).as("test data").contains("监督管理方面的培训");
		String r481 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r481).as("test data").contains("监督行为规范的管理");
		String r482 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r482).as("test data").contains("3.2.6 组长发出指令和后续贯彻的沟通及协调能力不足");
		String r483 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r483).as("test data").contains("不适用");
		String r484 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li"))).getText();
		softly.assertThat(r484).as("test data").contains("访谈下属？");
		String r485 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r485).as("test data").contains("监督管理方面的培训");
		String r486 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r486).as("test data").contains("监督行为规范的管理");
		return verifyChinese;
	}
}
