import org.assertj.core.api.SoftAssertions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class HiRCAChinese26 {

	public void chineseReport1stPath_hc26 (WebDriver driver, SoftAssertions softly) throws Exception {

		WebDriverWait wait = new WebDriverWait(driver,30);
		//1.11
		String r380 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[15]/td[1]"))).getText();
		softly.assertThat(r380).as("test data").contains("1.11 这个错为何是现在发生而不是以前发生？");
		String r381 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[15]/td[2]"))).getText();
		softly.assertThat(r381).as("test data").contains("新程序的使用未有妥当培训");
		String r382 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[15]/td[3]"))).getText();
		softly.assertThat(r382).as("test data").contains("不适用");
		//3.9 table heading
		String heading19 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading19).as("test data").contains("可能促成因素");
		String heading20 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading20).as("test data").contains("支持证据");
		String heading21 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading21).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading22 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading22).as("test data").contains("可能的纠正行动");*/
		//3.9 table rows
		String r383 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r383).as("test data").contains("3.9.1 培训材料在适用性、及时性或实用性方面有所欠缺");
		String r2291 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r2291).as("test data").contains("不适用");
		String r2301 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2301).as("test data").contains("与类似组织对标？");
		String r2311 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2311).as("test data").contains("通过现场观察审查培训效果？");
		String r2321 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r2321).as("test data").contains("加强培训资源");
		String r2331 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r2331).as("test data").contains("开展作业任务分析，从而使培训材料、课程及时间与员工执行的任务相匹配");
		String r2341 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r2341).as("test data").contains("3.9.2 复训频率不高(>> 一年)");
		String r2351 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r2351).as("test data").contains("不适用");
		String r2361 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2361).as("test data").contains("复训频率是否是根据复杂程度和使用频率来确定的？");
		String r2371 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2371).as("test data").contains("复训的形式？");
		String r2381 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li"))).getText();
		softly.assertThat(r2381).as("test data").contains("增加复训频率，改善复训形式");
		String r2391 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r2391).as("test data").contains("3.9.3 部门管理层未充分参与培训材料的编写和培训的实施");
		String r2401 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r2401).as("test data").contains("不适用");
		String r2411 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2411).as("test data").contains("部门经理审查关于培训材料的意见？");
		String r2421 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2421).as("test data").contains("部门经理监督对上课情况？");
		String r2431 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li"))).getText();
		softly.assertThat(r2431).as("test data").contains("完善关于管理层参与培训材料编写或培训实施的相关要求");
		String r2441 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r2441).as("test data").contains("3.9.4 未将经验教训充分包含到培训中");
		String r2451 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r2451).as("test data").contains("不适用");
		String r2461 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r2461).as("test data").contains("审查对以往事件根本原因和共同原因的调查情况（从屏障、失误陷阱等角度）？");
		String r2471 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li"))).getText();
		softly.assertThat(r2471).as("test data").contains("提高对培训效果的审查");
		String r2481 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r2481).as("test data").contains("3.9.5 所需培训开展不充分（脱岗）");
		String r2491 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r2491).as("test data").contains("不适用");
		String r2501 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2501).as("test data").contains("培训签到表，%员工接受了培训？");
		String r2511 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2511).as("test data").contains("现场承包商没有经过培训？");
		String r2521 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r2521).as("test data").contains("完善承包商控制方针");
		String r2531 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r2531).as("test data").contains("完善培训资源");
		String r2541 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r2541).as("test data").contains("3.9.6 所需培训开展不充分（在岗）");
		String r2551 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r2551).as("test data").contains("不适用");
		String r2561 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r2561).as("test data").contains("在岗培训方针？");
		String r2571 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r2571).as("test data").contains("经验不足的员工没有经过培训？");
		String r2581 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r2581).as("test data").contains("完善在岗培训方针");
		String r2591 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[16]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r2591).as("test data").contains("完善培训资源");
		//1.12
		String r3801 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[17]/td[1]"))).getText();
		softly.assertThat(r3801).as("test data").contains("1.12 若班前会、工前会或交底会未执行，为什么？");
		String r3811 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[17]/td[2]"))).getText();
		softly.assertThat(r3811).as("test data").contains("违反程序规定未执行");
		String r3821 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[17]/td[3]"))).getText();
		softly.assertThat(r3821).as("test data").contains("不适用");
		//1.13
		String r38011 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[18]/td[1]"))).getText();
		softly.assertThat(r38011).as("test data").contains("1.13 错误的发生是否存在易出错精神状态或是高风险状态？");
		String r38111 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[18]/td[2]"))).getText();
		softly.assertThat(r38111).as("test data").contains("没有，请重新思考您的答案");
		String r384 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[18]/td[3]"))).getText();
		softly.assertThat(r384).as("test data").contains("不适用");
		//1.14
		String r385= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[19]/td[1]"))).getText();
		softly.assertThat(r385).as("test data").contains("1.14 组长是否固定开展经验反馈？");
		String r386 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[19]/td[2]"))).getText();
		softly.assertThat(r386).as("test data").contains("没有，但其他组长有");
		String r387 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[19]/td[3]"))).getText();
		softly.assertThat(r387).as("test data").contains("不适用");
		//3.2 table heading
		String heading221 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading221).as("test data").contains("可能促成因素");
		String heading23 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading23).as("test data").contains("支持证据");
		String heading24 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading24).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading25 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading25).as("test data").contains("可能的纠正行动");*/
		//3.2 table rows
		String r3151 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r3151).as("test data").contains("3.2.1 组长强化标准方面的管理能力不足");
		String r3161 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r3161).as("test data").contains("不适用");
		String r3171 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li"))).getText();
		softly.assertThat(r3171).as("test data").contains("访谈同事？");
		String r3181 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3181).as("test data").contains("监督管理方面的培训");
		String r3191 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3191).as("test data").contains("监督行为规范的管理");
		String r388 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r388).as("test data").contains("3.2.2 组长绩效反馈方面的管理能力不足");
		String r389 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r389).as("test data").contains("不适用");
		String r390 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r390).as("test data").contains("访谈同事？");
		String r391 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r391).as("test data").contains("监督管理方面的培训");
		String r392 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r392).as("test data").contains("监督行为规范的管理");
		String r393 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r393).as("test data").contains("3.2.3 组长召开经验反馈的管理技能不足");
		String r394 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r394).as("test data").contains("不适用");
		String r395 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li"))).getText();
		softly.assertThat(r395).as("test data").contains("访谈同事？");
		String r396 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r396).as("test data").contains("监督管理方面的培训");
		String r3291 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3291).as("test data").contains("监督行为规范的管理");
		String r3301 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r3301).as("test data").contains("3.2.4 组长在岗培训方面管理能力不足");
		String r3311 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r3311).as("test data").contains("不适用");
		String r3321 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r3321).as("test data").contains("访谈同事？");
		String r3331 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3331).as("test data").contains("监督管理方面的培训");
		String r3341 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3341).as("test data").contains("监督行为规范的管理");
		String r3351 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r3351).as("test data").contains("3.2.5 组长对团队缺点认识不足，缺乏相应弥补措施");
		String r3361 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r3361).as("test data").contains("不适用");
		String r3371 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r3371).as("test data").contains("访谈同事？");
		String r3381 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3381).as("test data").contains("监督管理方面的培训");
		String r3391 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3391).as("test data").contains("监督行为规范的管理");
		String r3401 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r3401).as("test data").contains("3.2.6 组长发出指令和后续贯彻的沟通及协调能力不足");
		String r3411 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r3411).as("test data").contains("不适用");
		String r3421 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li"))).getText();
		softly.assertThat(r3421).as("test data").contains("访谈下属？");
		String r3431 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r3431).as("test data").contains("监督管理方面的培训");
		String r3441 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[20]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r3441).as("test data").contains("监督行为规范的管理");
		//1.15
		String r397= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[21]/td[1]"))).getText();
		softly.assertThat(r397).as("test data").contains("1.15 始发事件是否有单项弱点？");
		String r398 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[21]/td[2]"))).getText();
		softly.assertThat(r398).as("test data").contains("有，但未提前识别");
		String r399 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[21]/td[3]"))).getText();
		softly.assertThat(r399).as("test data").contains("不适用");
		//3.6 table heading
		String heading27 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading27).as("test data").contains("可能促成因素");
		String heading28 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading28).as("test data").contains("支持证据");
		String heading29 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading29).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading30 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading30).as("test data").contains("可能的纠正行动");*/
		//3.6 table rows
		String r400 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r400).as("test data").contains("3.6.1 要求有遗漏");
		String r401 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r401).as("test data").contains("不适用");
		String r402 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r402).as("test data").contains("规范和标准？");
		String r403 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r403).as("test data").contains("规范和标准？");
		String r404 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r404).as("test data").contains("与其他项目之间的接口要求？");
		String r405 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r405).as("test data").contains("完善规则");
		String r406 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r406).as("test data").contains("开展程序设计方面的培训");
		String r407 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r407).as("test data").contains("3.6.2 运行条件有遗漏");
		String r408 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r408).as("test data").contains("不适用");
		String r409 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r409).as("test data").contains("规则适用的运行条件范围？");
		String r410 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r410).as("test data").contains("进入规则的前提条件？");
		String r411 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r411).as("test data").contains("退出规则的条件？");
		String r412 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r412).as("test data").contains("完善规则");
		String r413 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r413).as("test data").contains("开展程序设计方面的培训");
		String r414 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r414).as("test data").contains("3.6.3 假设有遗漏");
		String r415 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r415).as("test data").contains("不适用");
		String r416 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r416).as("test data").contains("假设未予以说明？");
		String r417 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r417).as("test data").contains("未要求在任务完成前对假设进行验证？");
		String r418 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r418).as("test data").contains("对未经验证的假设没有制定缓解措施？");
		String r419 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r419).as("test data").contains("完善规则");
		String r420 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r420).as("test data").contains("开展程序设计方面的培训");
		String r421 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r421).as("test data").contains("3.6.4 范围有遗漏");
		String r422 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r422).as("test data").contains("不适用");
		String r423 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r423).as("test data").contains("使用通用规则，缺少针对各种特殊情况的具体描述？");
		String r424 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r424).as("test data").contains("步骤遗漏？");
		String r425 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r425).as("test data").contains("遗漏了碰到异常情况时需采取的行动？");
		String r426 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r426).as("test data").contains("完善规则");
		String r427 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r427).as("test data").contains("开展程序设计方面的培训");
		String r428 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r428).as("test data").contains("3.6.5 试验或测量有遗漏");
		String r429 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r429).as("test data").contains("不适用");
		String r430 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r430).as("test data").contains("遗漏了用于验收是否正确执行的相关试验或测量？");
		String r431 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r431).as("test data").contains("完善规则");
		String r432 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r432).as("test data").contains("开展程序设计方面的培训");
		String r433 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r433).as("test data").contains("3.6.6 遗漏以下信息: (1) 目的; (2) 先决条件; (3) 定义; (4) 经验反馈用");
		softly.assertThat(r433).as("test data").contains("不准做清单");
		softly.assertThat(r433).as("test data").contains("体现; (5) 参考资料; (6) 要求使用者反馈");
		String r434 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r434).as("test data").contains("不适用");
		String r435 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r435).as("test data").contains("调查程序编写者");
		String r436 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r436).as("test data").contains("调查程序设计编写培训");
		String r437 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r437).as("test data").contains("开展程序设计编写培训");
		String r438 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r438).as("test data").contains("改善程序编写导则");
		String r439 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r439).as("test data").contains("3.6.7 审查不到位导致制度有遗漏项");
		String r440 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r440).as("test data").contains("不适用");
		String r441 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r441).as("test data").contains("调查程序审查者");
		String r442 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r442).as("test data").contains("调查程序审查培训");
		String r443 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li"))).getText();
		softly.assertThat(r443).as("test data").contains("开展程序审查培训");
		String r444 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[1]"))).getText();
		softly.assertThat(r444).as("test data").contains("3.6.8 根本原因分析不到位导致制度有遗漏项");
		String r445 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[2]"))).getText();
		softly.assertThat(r445).as("test data").contains("不适用");
		String r446 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r446).as("test data").contains("调查事件调查者");
		String r447 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r447).as("test data").contains("调查事件根本原因培训");
		String r448 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li"))).getText();
		softly.assertThat(r448).as("test data").contains("开展根本原因培训");
		String r449 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r449).as("test data").contains("3.6.9 纠正措施执行不到位导致制度有遗漏项");
		String r450 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r450).as("test data").contains("不适用");
		String r451 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r451).as("test data").contains("调查纠正措施主管");
		String r452 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r452).as("test data").contains("调查纠正措施制度缺陷");
		String r453 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[22]/td[1]/div/table/tbody/tr[9]/td[4]/ul/li"))).getText();
		softly.assertThat(r453).as("test data").contains("改善纠正措施制度的监督与执行");
		//1.16
		String r454= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[23]/td[1]"))).getText();
		softly.assertThat(r454).as("test data").contains("1.16 事件是与组长监督管理不当有关？");
		String r455 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[23]/td[2]"))).getText();
		softly.assertThat(r455).as("test data").contains("是，跟其他组长相比下有缺失");
		String r456 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[23]/td[3]"))).getText();
		softly.assertThat(r456).as("test data").contains("不适用");
		//3.2 table heading
		String heading31 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading31).as("test data").contains("可能促成因素");
		String heading32 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading32).as("test data").contains("支持证据");
		String heading33 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading33).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading34 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading34).as("test data").contains("可能的纠正行动");*/
		//3.2 table rows
		String r457 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r457).as("test data").contains("3.2.1 组长强化标准方面的管理能力不足");
		String r458 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r458).as("test data").contains("不适用");
		String r459 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li"))).getText();
		softly.assertThat(r459).as("test data").contains("访谈同事？");
		String r460 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r460).as("test data").contains("监督管理方面的培训");
		String r461 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r461).as("test data").contains("监督行为规范的管理");
		String r462 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r462).as("test data").contains("3.2.2 组长绩效反馈方面的管理能力不足");
		String r463 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r463).as("test data").contains("不适用");
		String r464 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r464).as("test data").contains("访谈同事？");
		String r465 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r465).as("test data").contains("监督管理方面的培训");
		String r466 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r466).as("test data").contains("监督行为规范的管理");
		String r467 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r467).as("test data").contains("3.2.3 组长召开经验反馈的管理技能不足");
		String r468 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r468).as("test data").contains("不适用");
		String r469 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li"))).getText();
		softly.assertThat(r469).as("test data").contains("访谈同事？");
		String r470 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r470).as("test data").contains("监督管理方面的培训");
		String r471 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r471).as("test data").contains("监督行为规范的管理");
		String r472 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r472).as("test data").contains("3.2.4 组长在岗培训方面管理能力不足");
		String r473 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r473).as("test data").contains("不适用");
		String r474 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r474).as("test data").contains("访谈同事？");
		String r475 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r475).as("test data").contains("监督管理方面的培训");
		String r476 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r476).as("test data").contains("监督行为规范的管理");
		String r477 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r477).as("test data").contains("3.2.5 组长对团队缺点认识不足，缺乏相应弥补措施");
		String r478 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r478).as("test data").contains("不适用");
		String r479 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r479).as("test data").contains("访谈同事？");
		String r480 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r480).as("test data").contains("监督管理方面的培训");
		String r481 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r481).as("test data").contains("监督行为规范的管理");
		String r482 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r482).as("test data").contains("3.2.6 组长发出指令和后续贯彻的沟通及协调能力不足");
		String r483 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r483).as("test data").contains("不适用");
		String r484 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li"))).getText();
		softly.assertThat(r484).as("test data").contains("访谈下属？");
		String r485 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r485).as("test data").contains("监督管理方面的培训");
		String r486 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[24]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r486).as("test data").contains("监督行为规范的管理");
		//1.17
		String r487= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[25]/td[1]"))).getText();
		softly.assertThat(r487).as("test data").contains("1.17 事件是与经理管理不当有关？");
		String r488 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[25]/td[2]"))).getText();
		softly.assertThat(r488).as("test data").contains("有");
		String r489 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[25]/td[3]"))).getText();
		softly.assertThat(r489).as("test data").contains("不适用");
		//3.3 table heading
		String heading35 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading35).as("test data").contains("可能促成因素");
		String heading36 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading36).as("test data").contains("支持证据");
		String heading37 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading37).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading38 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading38).as("test data").contains("可能的纠正行动");*/
		//3.3 table rows
		String r490 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r490).as("test data").contains("3.3.1 经理团队资源分配不到位");
		String r491 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r491).as("test data").contains("不适用");
		String r492 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r492).as("test data").contains("是否一些工作组工作量过多，而另一些工作组工作量过少？");
		String r493 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r493).as("test data").contains("分配工作更多的是为了纠正问题，而不是防治问题？");
		String r495 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li"))).getText();
		softly.assertThat(r495).as("test data").contains("提升管理技能，完善资源分配体系");
		String r497 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r497).as("test data").contains("3.3.2 经理团队所需培训开展不充分");
		String r498 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r498).as("test data").contains("不适用");
		String r499 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r499).as("test data").contains("培训计划是否从提高效率和提高质量两个方面考虑？");
		String r500 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li"))).getText();
		softly.assertThat(r500).as("test data").contains("成立培训计划委员会");
		String r501 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r501).as("test data").contains("3.3.3 经理团队问责制不到位");
		String r502 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r502).as("test data").contains("不适用");
		String r503 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r503).as("test data").contains("PM&T是否充分？");
		String r504 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r504).as("test data").contains("JO是否充分？");
		String r505 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r505).as("test data").contains("RCA是否充分？");
		String r506 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[4]"))).getText();
		softly.assertThat(r506).as("test data").contains("ORRA是否充分？");
		String r507 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li"))).getText();
		softly.assertThat(r507).as("test data").contains("完善问责制");
		String r508 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r508).as("test data").contains("3.3.4 经理团队对确定工作优先级和计划方面不到位");
		String r509 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r509).as("test data").contains("不适用");
		String r510 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r510).as("test data").contains("工作流程中没有包括工作优先级的确定？");
		String r511 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r511).as("test data").contains("优先级确定标准在时间、范围（质量）和成本三个方面没有平衡好？");
		String r512 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li"))).getText();
		softly.assertThat(r512).as("test data").contains("完善管理优先级确定和计划体系？");
		String r513 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r513).as("test data").contains("3.3.5 经理管理人员对以下标准制定不充分：(1) 行为规范 (2) 程序和屏障");
		String r514 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r514).as("test data").contains("不适用");
		String r515 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r515).as("test data").contains("自我分析（自评）？");
		String r516 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r516).as("test data").contains("与表现优秀者对标？");
		String r517 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r517).as("test data").contains("开展关于标准设定的管理培训");
		String r518 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r518).as("test data").contains("开展关于程序和保护屏障设计的培训");
		String r519 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r519).as("test data").contains("3.3.6 经理团队绩效跟踪与趋势分析不到位");
		String r520 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r520).as("test data").contains("不适用");
		String r521 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r521).as("test data").contains("KPI不充分？");
		String r522 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r522).as("test data").contains("没有定期开展共因分析？");
		String r523 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r523).as("test data").contains("未对类似事件或失误进行趋势分析？");
		String r524 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r524).as("test data").contains("定期开展共因分析");
		String r525 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r525).as("test data").contains("改善绩效跟踪与趋势分析项目");
		String r526 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[3]"))).getText();
		softly.assertThat(r526).as("test data").contains("完善KPI");
		String r527 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r527).as("test data").contains("3.3.7 经理团队内未充分建立关于团队合作的共同目标、共同利益和共同责任");
		String r528 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r528).as("test data").contains("不适用");
		String r529 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r529).as("test data").contains("经理之间的接口问题？");
		String r530 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r530).as("test data").contains("主管或经理之间存在不和？");
		String r531 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r531).as("test data").contains("因两个管理团队之间接口问题，导致工作没有做？");
		String r532 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r532).as("test data").contains("开展组织设计方面的管理培训");
		String r533 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r533).as("test data").contains("在经理人员之间建立共同目标、共同利益和共同责任");
		String r534 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[1]"))).getText();
		softly.assertThat(r534).as("test data").contains("3.3.8 经理团队纠正行动不足");
		String r535 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[2]"))).getText();
		softly.assertThat(r535).as("test data").contains("不适用");
		String r536 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r536).as("test data").contains("根本原因分析不足导致事件重发？");
		String r537 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r537).as("test data").contains("没有注意到关键的在变化的问题导致未能解决紧急问题？");
		String r538 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r538).as("test data").contains("纠正行动制定过多导致大量纠正行动仍然积压？");
		String r539 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r539).as("test data").contains("提高纠正行动计划的落实");
		String r540 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r540).as("test data").contains("改善根本原因分析方法");
		String r541 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[3]"))).getText();
		softly.assertThat(r541).as("test data").contains("完善突发紧急问题（危机）管理机制");
		String r542 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r542).as("test data").contains("3.3.9 经理团队垂直沟通体系不完善");
		String r543 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r543).as("test data").contains("不适用");
		String r544 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r544).as("test data").contains("方针培训？");
		String r545 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r545).as("test data").contains("对员工的管理指导？");
		String r546 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r546).as("test data").contains("传达给员工的工作指令不充分？");
		String r547 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[4]"))).getText();
		softly.assertThat(r547).as("test data").contains("是否定期召开员工会议？");
		String r548 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[9]/td[4]/ul/li"))).getText();
		softly.assertThat(r548).as("test data").contains("完善垂直沟通体系");
		String r549 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[10]/td[1]"))).getText();
		softly.assertThat(r549).as("test data").contains("3.3.10 经理团队横向沟通体系不完善");
		String r550 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[10]/td[2]"))).getText();
		softly.assertThat(r550).as("test data").contains("不适用");
		String r551 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[10]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r551).as("test data").contains("共同目标和共同利益不充分？");
		String r552 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[10]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r552).as("test data").contains("程序设计不当？");
		String r553 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r553).as("test data").contains("完善程序设计");
		String r554 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[26]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r554).as("test data").contains("制定共同目标和共同利益");
		//1.18
		String r555= wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[27]/td[1]"))).getText();
		softly.assertThat(r555).as("test data").contains("1.18 事件是因程序规则有误导致？");
		String r556 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[27]/td[2]"))).getText();
		softly.assertThat(r556).as("test data").contains("是");
		String r557 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[27]/td[3]"))).getText();
		softly.assertThat(r557).as("test data").contains("不适用");		
	}
}
