import org.assertj.core.api.SoftAssertions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class HiRCAChinese25 {

	public void chineseReport1stPath_hc25 (WebDriver driver, SoftAssertions softly) throws Exception {

		WebDriverWait wait = new WebDriverWait(driver,30);
		//3.18
		String r166 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r166).as("test data").contains("3.18.1 盲目信任: 关键信息使用质疑的态度QV&V");
		softly.assertThat(r166).as("test data").contains("不到位");
		String r167 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r167).as("test data").contains("不适用");
		String r168 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r168).as("test data").contains("审查培训材料？");
		String r169 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r169).as("test data").contains("审查以往类似事件？");
		String r170 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li"))).getText();
		softly.assertThat(r170).as("test data").contains("提高质疑的态度QV&V");
		softly.assertThat(r170).as("test data").contains(" 培训");
		String r171 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r171).as("test data").contains("3.18.2 过度自信: (1) 高估自我效能; (2) 未意识到影响变化; (3) 未寻求他人智慧; (4) 没有从过去中学习; (5) 缺少屏障预防错误发生");
		String r172 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r172).as("test data").contains("不适用");
		String r173 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r173).as("test data").contains("执行首次执行的任务而没有仔细规划?");
		String r174 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r174).as("test data").contains("过去有过超出能力工作的事件?");
		String r175 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r175).as("test data").contains("对设计工作推断不当而未执行适当试验?");
		String r176 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li"))).getText();
		softly.assertThat(r176).as("test data").contains("行为培训，避免过度自信");
		String r177 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[8]/td[1]"))).getText();
		softly.assertThat(r177).as("test data").contains("3.18.3 眼不见心不想: (1) 对低概率/高风险事件的风险控制不到位; (2) 忽略与绩效指标或激励无关的问题; (3) 因忽略相关风险而未设置屏障");
		String r178 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[8]/td[2]"))).getText();
		softly.assertThat(r178).as("test data").contains("不适用");
		String r179 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r179).as("test data").contains("因忽略相关风险而未设置屏障");
		String r180 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r180).as("test data").contains("审查管理监督或项目委员会会议纪要?");
		String r181 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r181).as("test data").contains("改善风险控制项目(");
		String r182 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r182).as("test data").contains("完善PM&T体系");
		String r183 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r183).as("test data").contains("3.18.4 未能及时止损: (1) 因自满和（或）无知，捍卫过去错误的决定或犹豫不决; (2) 期望通过重复同样的问题处理方法、标准或策略来实现不同的结果");
		String r184 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r184).as("test data").contains("不适用");
		String r185 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r185).as("test data").contains("审查管理监督或项目委员会会议纪要?");
		String r186 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[9]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r186).as("test data").contains("审查以往决策的有效性，提高管理监督");
		String r187 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[10]/td[1]"))).getText();
		softly.assertThat(r187).as("test data").contains("3.18.5 陷入两选一的陷阱: 决策、问题解决或计划不充分，未能确保全面考虑多个选择方案进行分析");
		String r188 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[10]/td[2]"))).getText();
		softly.assertThat(r188).as("test data").contains("不适用");
		String r189 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[10]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r189).as("test data").contains("审查管理监督或项目委员会会议纪要?");
		String r190 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[3]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r190).as("test data").contains("提高决策、问题解决和计划的结构（委员会）和流程");
		//1.3
		String r191 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r191).as("test data").contains("1.3 若为规则型错误，是否为有意违规还是无意违规？");
		String r192 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r192).as("test data").contains("不适用");
		String r193 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[4]/td[3]"))).getText();
		softly.assertThat(r193).as("test data").contains("不适用");
		//1.4
		String r194 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r194).as("test data").contains("1.4 此无意违规是粗心导致还是程序不当导致？");
		String r195 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r195).as("test data").contains("不适用");
		String r196 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[5]/td[3]"))).getText();
		softly.assertThat(r196).as("test data").contains("不适用");
		//1.5
		String r197 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r197).as("test data").contains("1.5 若我是犯错者，我是否会犯同样的错？");
		String r198 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r198).as("test data").contains("不适用");
		String r199 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[6]/td[3]"))).getText();
		softly.assertThat(r199).as("test data").contains("不适用");
		//1.6
		String r200 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r200).as("test data").contains("1.6 犯错者违规时是否有旁人观看？");
		String r201 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r201).as("test data").contains("有");
		String r202 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[7]/td[3]"))).getText();
		softly.assertThat(r202).as("test data").contains("不适用");
		//3.15 table heading
		String heading7 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading7).as("test data").contains("可能促成因素");
		String heading8 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading8).as("test data").contains("支持证据");
		String heading9 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading9).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading10 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading10).as("test data").contains("可能的纠正行动");*/
		//3.15 table rows
		String r203 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r203).as("test data").contains("3.15.1 员工未经过相互指导的培训，或纠正他人违规情况的培训");
		String r204 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r204).as("test data").contains("不适用");
		String r205 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li"))).getText();
		softly.assertThat(r205).as("test data").contains("审查相关培训？");
		String r206 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li"))).getText();
		softly.assertThat(r206).as("test data").contains("同事互助提醒（好文化）培训");
		String r207 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r207).as("test data").contains("3.15.2 未要求员工对纠正他人违规的情况承担责任");
		String r208 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r208).as("test data").contains("不适用");
		String r209 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r209).as("test data").contains("审查关于同事互助提醒（好文化）的管理期望和标准？");
		String r210 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li"))).getText();
		softly.assertThat(r210).as("test data").contains("建立关于同事互助提醒（好文化）的管理期望");
		String r211 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r211).as("test data").contains("3.15.3 员工未充分理解相关行为规范");
		String r212 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r212).as("test data").contains("不适用");
		String r213 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li"))).getText();
		softly.assertThat(r213).as("test data").contains("观察工前会和工作的执行，以了解对行为规范的管理强化情况？");
		String r214 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r214).as("test data").contains("行为规范培训");
		String r215 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r215).as("test data").contains("采用行为规范提醒物");
		String r216 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[3]"))).getText();
		softly.assertThat(r216).as("test data").contains("采用禁止事项警告清单");
		String r217 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r217).as("test data").contains("3.15.4 主管未到现场强化");
		softly.assertThat(r217).as("test data").contains("同事指导");
		String r218 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r218).as("test data").contains("不适用");
		String r219 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r219).as("test data").contains("观察工前会和工作的执行，以了解对行为规范的管理强化情况？");
		String r220 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r220).as("test data").contains("监督管理能力培训");
		String r221 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[8]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r221).as("test data").contains("就监督管理强化，对管理者实施问责");
		//1.7
		String r222 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r222).as("test data").contains("1.7 这个错误是否可以透过自检或独立检查避免？");
		String r223 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r223).as("test data").contains("不能");
		String r224 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[9]/td[3]"))).getText();
		softly.assertThat(r224).as("test data").contains("不适用");
		//1.8
		String r225 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[10]/td[1]"))).getText();
		softly.assertThat(r225).as("test data").contains("1.8 犯错人员是否受过培训知道如何管理易出错精神状态和高风险？");
		String r226 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[10]/td[2]"))).getText();
		softly.assertThat(r226).as("test data").contains("没有");
		String r227 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[10]/td[3]"))).getText();
		softly.assertThat(r227).as("test data").contains("不适用");
		//3.9 table heading
		String heading11 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading11).as("test data").contains("可能促成因素");
		String heading12 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading12).as("test data").contains("支持证据");
		String heading13 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading13).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading14 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading14).as("test data").contains("可能的纠正行动");*/
		//3.9 table rows
		String r228 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r228).as("test data").contains("3.9.1 培训材料在适用性、及时性或实用性方面有所欠缺");
		String r229 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r229).as("test data").contains("不适用");
		String r230 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r230).as("test data").contains("与类似组织对标？");
		String r231 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r231).as("test data").contains("通过现场观察审查培训效果？");
		String r232 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r232).as("test data").contains("加强培训资源");
		String r233 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r233).as("test data").contains("开展作业任务分析，从而使培训材料、课程及时间与员工执行的任务相匹配");
		String r234 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r234).as("test data").contains("3.9.2 复训频率不高(>> 一年)");
		String r235 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r235).as("test data").contains("不适用");
		String r236 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r236).as("test data").contains("复训频率是否是根据复杂程度和使用频率来确定的？");
		String r237 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r237).as("test data").contains("复训的形式？");
		String r238 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li"))).getText();
		softly.assertThat(r238).as("test data").contains("增加复训频率，改善复训形式");
		String r239 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r239).as("test data").contains("3.9.3 部门管理层未充分参与培训材料的编写和培训的实施");
		String r240 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r240).as("test data").contains("不适用");
		String r241 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r241).as("test data").contains("部门经理审查关于培训材料的意见？");
		String r242 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r242).as("test data").contains("部门经理监督对上课情况？");
		String r243 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li"))).getText();
		softly.assertThat(r243).as("test data").contains("完善关于管理层参与培训材料编写或培训实施的相关要求");
		String r244 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r244).as("test data").contains("3.9.4 未将经验教训充分包含到培训中");
		String r245 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r245).as("test data").contains("不适用");
		String r246 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r246).as("test data").contains("审查对以往事件根本原因和共同原因的调查情况（从屏障、失误陷阱等角度）？");
		String r247 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li"))).getText();
		softly.assertThat(r247).as("test data").contains("提高对培训效果的审查");
		String r248 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r248).as("test data").contains("3.9.5 所需培训开展不充分（脱岗）");
		String r249 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r249).as("test data").contains("不适用");
		String r250 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r250).as("test data").contains("培训签到表，%员工接受了培训？");
		String r251 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r251).as("test data").contains("现场承包商没有经过培训？");
		String r252 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r252).as("test data").contains("完善承包商控制方针");
		String r253 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r253).as("test data").contains("完善培训资源");
		String r254 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r254).as("test data").contains("3.9.6 所需培训开展不充分（在岗）");
		String r255 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r255).as("test data").contains("不适用");
		String r256 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r256).as("test data").contains("在岗培训方针？");
		String r257 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r257).as("test data").contains("经验不足的员工没有经过培训？");
		String r258 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r258).as("test data").contains("完善在岗培训方针");
		String r259 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r259).as("test data").contains("完善培训资源");
		//3.10
		String r260 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r260).as("test data").contains("3.10.1 关键岗位员工的作业授权不充分");
		String r261 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r261).as("test data").contains("不适用");
		String r262 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li"))).getText();
		softly.assertThat(r262).as("test data").contains("授权政策和证书？");
		String r263 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li"))).getText();
		softly.assertThat(r263).as("test data").contains("完善作业授权");
		String r264 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[8]/td[1]"))).getText();
		softly.assertThat(r264).as("test data").contains("3.10.2 关键岗位主管和（或）经理授权不充分");
		String r265 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[8]/td[2]"))).getText();
		softly.assertThat(r265).as("test data").contains("不适用");
		String r266 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li"))).getText();
		softly.assertThat(r266).as("test data").contains("授权政策和证书？");
		String r267 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li"))).getText();
		softly.assertThat(r267).as("test data").contains("完善主管和经理的岗位授权");
		String r268 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r268).as("test data").contains("3.10.3 供应商服务（QA/RC、来源检查）授权不充分");
		String r269 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r269).as("test data").contains("不适用");
		String r270 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li"))).getText();
		softly.assertThat(r270).as("test data").contains("授权政策和证书？");
		String r271 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[9]/td[4]/ul/li"))).getText();
		softly.assertThat(r271).as("test data").contains("完善供应商控制制度");
		String r272 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[10]/td[1]"))).getText();
		softly.assertThat(r272).as("test data").contains("3.10.4 现场供应商人员授权不充分");
		String r273 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[10]/td[2]"))).getText();
		softly.assertThat(r273).as("test data").contains("不适用");
		String r274 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[10]/td[3]/ul/li"))).getText();
		softly.assertThat(r274).as("test data").contains("授权政策和证书？");
		String r275 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li"))).getText();
		softly.assertThat(r275).as("test data").contains("完善供应商控制制度");
		String r276 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[11]/td[1]"))).getText();
		softly.assertThat(r276).as("test data").contains("3.10.5 培训教员授权不充分");
		String r277 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[11]/td[2]"))).getText();
		softly.assertThat(r277).as("test data").contains("不适用");
		String r278 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[11]/td[3]/ul/li"))).getText();
		softly.assertThat(r278).as("test data").contains("授权政策和证书？");
		String r279 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[11]/td[4]/ul/li"))).getText();
		softly.assertThat(r279).as("test data").contains("完善有关培训教员资格授权的管理标准与方针");
		//3.11
		String r280 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[12]/td[1]"))).getText();
		softly.assertThat(r280).as("test data").contains("3.11.1 绩效跟踪与趋势分析(PM&T)以及给员工的反馈不到位");
		String r281 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[12]/td[2]"))).getText();
		softly.assertThat(r281).as("test data").contains("不适用");
		String r282 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[12]/td[3]/ul/li"))).getText();
		softly.assertThat(r282).as("test data").contains("向员工反馈绩效趋势结果？");
		String r283 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[12]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r283).as("test data").contains("完善趋势分析体系");
		String r284 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[12]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r284).as("test data").contains("完善趋势反馈");
		String r285 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[1]"))).getText();
		softly.assertThat(r285).as("test data").contains("3.11.2 即时反馈和持续强化(IF&CR)的管理技能不到位");
		String r286 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[2]"))).getText();
		softly.assertThat(r286).as("test data").contains("不适用");
		String r287 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r287).as("test data").contains("花在现场观察和监督工作的时间是否足够？");
		String r288 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r288).as("test data").contains("标准的持续强化？");
		String r289 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r289).as("test data").contains("观察到偏差时，是否及时反馈？");
		String r290 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[3]/ul/li[4]"))).getText();
		softly.assertThat(r290).as("test data").contains("正面反馈多余负面反馈？");
		String r291 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r291).as("test data").contains("提高主管人员的问责意识");
		String r292 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[13]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r292).as("test data").contains("改善关于管理技能的培训");
		String r293 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[14]/td[1]"))).getText();
		softly.assertThat(r293).as("test data").contains("3.11.3 用于绩效控制的奖惩制度不到位");
		String r294 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[14]/td[2]"))).getText();
		softly.assertThat(r294).as("test data").contains("不适用");
		String r295 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[14]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r295).as("test data").contains("奖惩制度是否及时？");
		String r296 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[14]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r296).as("test data").contains("奖惩制度是否公平？");
		String r297 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[14]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r297).as("test data").contains("奖惩制度是否坚定？");
		String r298 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[14]/td[4]/ul/li"))).getText();
		softly.assertThat(r298).as("test data").contains("完善奖惩制度");
		String r299 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[15]/td[1]"))).getText();
		softly.assertThat(r299).as("test data").contains("3.11.4 问题报告、RCA和纠正行动不到位，给员工的反馈不到位");
		String r300 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[15]/td[2]"))).getText();
		softly.assertThat(r300).as("test data").contains("不适用");
		String r301 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[15]/td[3]/ul/li"))).getText();
		softly.assertThat(r301).as("test data").contains("核实汇报分析的小事件数量比例以及受伤数量");
		String r302 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[15]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r302).as("test data").contains("在问题报告政策中要求包含一切问题和及时性");
		String r303 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[15]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r303).as("test data").contains("RCA培训和授权");
		String r304 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[15]/td[4]/ul/li[3]"))).getText();
		softly.assertThat(r304).as("test data").contains("改善对RCA结果的反馈");
		String r305 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[16]/td[1]"))).getText();
		softly.assertThat(r305).as("test data").contains("3.11.5 现场观察不充分，给员工的反馈不到位");
		String r306 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[16]/td[2]"))).getText();
		softly.assertThat(r306).as("test data").contains("不适用");
		String r307 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[16]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r307).as("test data").contains("各部门均建立了现场观察指导制度？");
		String r308 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[16]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r308).as("test data").contains("对过去现场观察指导结果的有效性审查？");
		String r309 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[16]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r309).as("test data").contains("花在现场观察指导上的时间？");
		String r310 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[16]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r310).as("test data").contains("针对现场观察结果，改善给员工的反馈");
		String r311 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[11]/td[1]/div/table/tbody/tr[16]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r311).as("test data").contains("改进现场观察员的制度和TQA");
		//1.9
		String r312 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[12]/td[1]"))).getText();
		softly.assertThat(r312).as("test data").contains("1.9 犯错者在事后是否有经组长或管理层问责？");
		String r313 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[12]/td[2]"))).getText();
		softly.assertThat(r313).as("test data").contains("没有");
		String r314 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[12]/td[3]"))).getText();
		softly.assertThat(r314).as("test data").contains("不适用");
		//3.2 table heading
		String heading15 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/thead/tr/th[1]"))).getText();
		softly.assertThat(heading15).as("test data").contains("可能促成因素");
		String heading16 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/thead/tr/th[2]"))).getText();
		softly.assertThat(heading16).as("test data").contains("支持证据");
		String heading17 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/thead/tr/th[3]"))).getText();
		softly.assertThat(heading17).as("test data").contains("进一步调查");
		
		/*am_not applicable
		String heading18 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/thead/tr/th[4]"))).getText();
		softly.assertThat(heading18).as("test data").contains("可能的纠正行动");*/
		//3.2 table rows
		String r315 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[1]"))).getText();
		softly.assertThat(r315).as("test data").contains("3.2.1 组长强化标准方面的管理能力不足");
		String r316 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[2]"))).getText();
		softly.assertThat(r316).as("test data").contains("不适用");
		String r317 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[3]/ul/li"))).getText();
		softly.assertThat(r317).as("test data").contains("访谈同事？");
		String r318 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r318).as("test data").contains("监督管理方面的培训");
		String r319 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[1]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r319).as("test data").contains("监督行为规范的管理");
		String r320 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[1]"))).getText();
		softly.assertThat(r320).as("test data").contains("3.2.2 组长绩效反馈方面的管理能力不足");
		String r321 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[2]"))).getText();
		softly.assertThat(r321).as("test data").contains("不适用");
		String r322 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[3]/ul/li"))).getText();
		softly.assertThat(r322).as("test data").contains("访谈同事？");
		String r323 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r323).as("test data").contains("监督管理方面的培训");
		String r324 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[2]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r324).as("test data").contains("监督行为规范的管理");
		String r325 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[1]"))).getText();
		softly.assertThat(r325).as("test data").contains("3.2.3 组长召开经验反馈的管理技能不足");
		String r326 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[2]"))).getText();
		softly.assertThat(r326).as("test data").contains("不适用");
		String r327 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[3]/ul/li"))).getText();
		softly.assertThat(r327).as("test data").contains("访谈同事？");
		String r328 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r328).as("test data").contains("监督管理方面的培训");
		String r329 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[3]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r329).as("test data").contains("监督行为规范的管理");
		String r330 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[1]"))).getText();
		softly.assertThat(r330).as("test data").contains("3.2.4 组长在岗培训方面管理能力不足");
		String r331 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[2]"))).getText();
		softly.assertThat(r331).as("test data").contains("不适用");
		String r332 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[3]/ul/li"))).getText();
		softly.assertThat(r332).as("test data").contains("访谈同事？");
		String r333 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r333).as("test data").contains("监督管理方面的培训");
		String r334 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[4]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r334).as("test data").contains("监督行为规范的管理");
		String r335 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[1]"))).getText();
		softly.assertThat(r335).as("test data").contains("3.2.5 组长对团队缺点认识不足，缺乏相应弥补措施");
		String r336 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[2]"))).getText();
		softly.assertThat(r336).as("test data").contains("不适用");
		String r337 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[3]/ul/li"))).getText();
		softly.assertThat(r337).as("test data").contains("访谈同事？");
		String r338 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r338).as("test data").contains("监督管理方面的培训");
		String r339 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[5]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r339).as("test data").contains("监督行为规范的管理");
		String r340 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[1]"))).getText();
		softly.assertThat(r340).as("test data").contains("3.2.6 组长发出指令和后续贯彻的沟通及协调能力不足");
		String r341 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[2]"))).getText();
		softly.assertThat(r341).as("test data").contains("不适用");
		String r342 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[3]/ul/li"))).getText();
		softly.assertThat(r342).as("test data").contains("访谈下属？");
		String r343 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r343).as("test data").contains("监督管理方面的培训");
		String r344 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[6]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r344).as("test data").contains("监督行为规范的管理");
		//3.11
		String r345 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[1]"))).getText();
		softly.assertThat(r345).as("test data").contains("3.11.1 绩效跟踪与趋势分析(PM&T)以及给员工的反馈不到位");
		String r346 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[2]"))).getText();
		softly.assertThat(r346).as("test data").contains("不适用");
		String r347 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[3]/ul/li"))).getText();
		softly.assertThat(r347).as("test data").contains("向员工反馈绩效趋势结果？");
		String r348 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r348).as("test data").contains("完善趋势分析体系");
		String r349 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[7]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r349).as("test data").contains("完善趋势反馈");
		String r350 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[1]"))).getText();
		softly.assertThat(r350).as("test data").contains("3.11.2 即时反馈和持续强化(IF&CR)的管理技能不到位");
		String r351 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[2]"))).getText();
		softly.assertThat(r351).as("test data").contains("不适用");
		String r352 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r352).as("test data").contains("花在现场观察和监督工作的时间是否足够？");
		String r353 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r353).as("test data").contains("标准的持续强化？");
		String r354 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r354).as("test data").contains("观察到偏差时，是否及时反馈？");
		String r355 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[3]/ul/li[4]"))).getText();
		softly.assertThat(r355).as("test data").contains("正面反馈多余负面反馈？");
		String r356 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r356).as("test data").contains("提高主管人员的问责意识");
		String r357 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[8]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r357).as("test data").contains("改善关于管理技能的培训");
		String r358 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[1]"))).getText();
		softly.assertThat(r358).as("test data").contains("3.11.3 用于绩效控制的奖惩制度不到位");
		String r359 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[2]"))).getText();
		softly.assertThat(r359).as("test data").contains("不适用");
		String r360 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r360).as("test data").contains("奖惩制度是否及时？");
		String r361 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r361).as("test data").contains("奖惩制度是否公平？");
		String r362 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r362).as("test data").contains("奖惩制度是否坚定？");
		String r363 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[9]/td[4]/ul/li"))).getText();
		softly.assertThat(r363).as("test data").contains("完善奖惩制度");
		String r364 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[1]"))).getText();
		softly.assertThat(r364).as("test data").contains("3.11.4 问题报告、RCA和纠正行动不到位，给员工的反馈不到位");
		String r365 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[2]"))).getText();
		softly.assertThat(r365).as("test data").contains("不适用");
		String r366 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[3]/ul/li"))).getText();
		softly.assertThat(r366).as("test data").contains("核实汇报分析的小事件数量比例以及受伤数量");
		String r367 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r367).as("test data").contains("在问题报告政策中要求包含一切问题和及时性");
		String r368 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r368).as("test data").contains("RCA培训和授权");
		String r369 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[10]/td[4]/ul/li[3]"))).getText();
		softly.assertThat(r369).as("test data").contains("改善对RCA结果的反馈");
		String r370 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[1]"))).getText();
		softly.assertThat(r370).as("test data").contains("3.11.5 现场观察不充分，给员工的反馈不到位");
		String r371 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[2]"))).getText();
		softly.assertThat(r371).as("test data").contains("不适用");
		String r372 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[3]/ul/li[1]"))).getText();
		softly.assertThat(r372).as("test data").contains("各部门均建立了现场观察指导制度？");
		String r373 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[3]/ul/li[2]"))).getText();
		softly.assertThat(r373).as("test data").contains("对过去现场观察指导结果的有效性审查？");
		String r374 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[3]/ul/li[3]"))).getText();
		softly.assertThat(r374).as("test data").contains("花在现场观察指导上的时间？");
		String r375 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[4]/ul/li[1]"))).getText();
		softly.assertThat(r375).as("test data").contains("针对现场观察结果，改善给员工的反馈");
		String r376 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[13]/td[1]/div/table/tbody/tr[11]/td[4]/ul/li[2]"))).getText();
		softly.assertThat(r376).as("test data").contains("改进现场观察员的制度和TQA");
		//1.10
		String r377 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[14]/td[1]"))).getText();
		softly.assertThat(r377).as("test data").contains("1.10 若有开班前会、工前会、交底会，为何犯错者未能意识到这个风险且缓解？");
		String r378 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[14]/td[2]"))).getText();
		softly.assertThat(r378).as("test data").contains("没有专心参与");
		String r379 = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@id='module-irca-rpt']/div[6]/table/tbody/tr[14]/td[3]"))).getText();
		softly.assertThat(r379).as("test data").contains("不适用");		
	}
}
